version: 2

models:
  - name: stg_income_tax_2024
    description: "Staging model for income tax rate and GDP per capita data for the year 2024, with country name normalization."
    columns:
      - name: Country
        description: "Standardized country name matching cost of living data"
        tests:
          - not_null
      - name: Year
        description: "Year of the fiscal data (2024)"
        tests:
          - not_null
      - name: Income_tax_rate
        description: "Income tax rate (as a float: 0.37 = 37%)"
        tests:
          - not_null
      - name: gdp_per_capita_usd_2023
        description: "GDP per capita in USD (2023 data used in 2024)"
        tests:
          - not_null

  - name: stg_cost_of_living_by_city_cleaned_Otmane
    description: "Staging model for cost of living indicators by city, with city name cleaning (ex: New York, NY → New York)."
    columns:
      - name: Country
        description: "Country where the city is located"
        tests:
          - not_null
      - name: City
        description: "Cleaned city name"
        tests:
          - not_null
      - name: Cost_of_Living_Index
        description: "Cost of living index (base 100 = New York)"