version: 2

sources:
  - name: data_cleaned
    database: z-score-467307
    schema: Data_cleaned
    tables:
      - name: Traffic_index_by_city_cleaned
      - name: temperature_ville_cleaned
      - name: Linguistic_diversity_index_by_country_cleaned
      - name: access_to_internet_country_cleaned