version: 2

sources:
  - name: Data_cleaned
    description: final tables
    tables:
      - name: Crime_safety_index_final_table
      - name: IDH_by_country_final_table
      - name: Cost_of_living_by_city_cleaned_Otmane
      - name: corruption_estimated_final_table
